### ISSUE TITLE
The subtitle search provides irrelevant results

### ISSUE THREAD

**Issue by tsiktsiris** [wako-unofficial-addons/helios#9] opened 2019-08-13 06:51 UTC
Video name is not passed correctly to the subtitle addons. 

I am using OpenMeta with Elementum .

**Comment by davidreedmichigan** [comment] 2019-08-20 07:12
If you use OpenMeta then you don't use Helios, cause Helios is sending the link directly on Kodi without use of any add-on. 
For your issue, the problem is that with Kodi I didn't find via their API, how to send video metadata. Hence Kodi doesn't know what is playing... What we have thought is to be able to copy/paste the video name in wako remote prompt. Still one more step but it's the simplest we've found

**Comment by davidreedmichigan** [comment] 2019-09-04 16:14
wako add this copy/paste option. I'm closing this

**Closed by davidreedmichigan** 2019-09-04 16:14 UTC
